apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngrok
spec:
  selector:
    matchLabels:
      app: ngrok
  replicas: 1
  template:
    metadata:
      labels:
        app: ngrok
    spec:
      containers:
        - name: ngrok
          image: wernight/ngrok:armhf
          command: ["ngrok"]
          args: ["http", "line-googlehome-bot-service"]
          ports:
            - containerPort: 4040
          env:
            - name: NGROK_AUTH
              valueFrom:
                secretKeyRef:
                  name: line-googlehome-bot-secret
                  key: ngrok_auth_key
            - name: NGROK_REGION
              value: ap
