apiVersion: v1
kind: Service
metadata:
  name: line-googlehome-bot-service
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: line-googlehome-bot
  type: NodePort
