apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngrok
spec:
  selector:
    matchLabels:
      app: ngrok
  replicas: 1
  template:
    metadata:
      labels:
        app: ngrok
    spec:
      containers:
        - name: ngrok
          image: wernight/ngrok:armhf
          ports:
            - containerPort: {{ .Values.ngrok.port }}
          env:
            - name: NGROK_AUTH
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: ngrok_auth_key
            - name: NGROK_REGION
              value: ap
            - name: NGROK_PORT
              value: {{ .Release.Name }}-service
